'use client';

import { FormEvent, useEffect, useState } from 'react';
import { TrainerShell } from '@/components/TrainerShell';
import { useTrainerSession } from '@/hooks/useTrainerSession';

export default function ConfiguracoesPage(){ return <TrainerShell><ConfiguracoesContent /></TrainerShell>; }
function ConfiguracoesContent(){ const {trainer,supabase,reload}=useTrainerSession(); const [data,setData]=useState<any>(null); const [gateway,setGateway]=useState<any>(null); useEffect(()=>{ if(!trainer)return; setData(trainer); supabase.from('trainer_payment_gateways').select('*').eq('trainer_id',trainer.id).maybeSingle().then(({data})=>setGateway(data));},[trainer]); async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!trainer)return; const f=new FormData(e.currentTarget); await supabase.from('trainers').update({full_name:f.get('full_name'),business_name:f.get('business_name'),business_phone:f.get('business_phone'),address:f.get('address')}).eq('id',trainer.id); reload();} async function connectGateway(provider:string){ if(!trainer)return; await supabase.from('trainer_payment_gateways').upsert({trainer_id:trainer.id,provider,status:'pending_onboarding',onboarding_url:'https://painel-do-gateway.example/onboarding'}); const {data}=await supabase.from('trainer_payment_gateways').select('*').eq('trainer_id',trainer.id).single(); setGateway(data); }
return <><div className="page-head"><div><span className="eyebrow">Configurações</span><h1>Configurações</h1><p>Dados do personal, assinatura, gateway, vídeos, notificações e suporte.</p></div></div><div className="grid-2"><div className="card panel-card"><h3>Dados do personal</h3><form className="form-grid" onSubmit={save}><div className="field"><label>Nome</label><input className="input" name="full_name" defaultValue={data?.full_name||''}/></div><div className="field"><label>Consultoria/studio</label><input className="input" name="business_name" defaultValue={data?.business_name||''}/></div><div className="field"><label>Telefone comercial</label><input className="input" name="business_phone" /></div><div className="field"><label>Endereço</label><input className="input" name="address" /></div><button className="btn btn-primary">Salvar</button></form></div><div className="card panel-card"><h3>Gateway de Pagamento</h3><p>Conecte uma conta para receber dos alunos. O sistema não armazena dados de cartão.</p><div className="actions"><button className="btn btn-primary" onClick={()=>connectGateway('mercadopago')}>Conectar Mercado Pago</button><button className="btn btn-secondary" onClick={()=>connectGateway('stripe_connect')}>Conectar Stripe Connect</button><button className="btn btn-secondary" onClick={()=>connectGateway('pagarme')}>Conectar Pagar.me</button></div>{gateway&&<div className="notice" style={{marginTop:12}}>Gateway: {gateway.provider} — status: {gateway.status}</div>}</div></div><div className="grid-3" style={{marginTop:18}}><div className="card panel-card"><h3>Assinatura PersonalOS</h3><p>Plano atual: {trainer?.plan_code}. Bloqueio após 3 dias de atraso.</p></div><div className="card panel-card"><h3>Vídeos e storage</h3><p>Bucket privado trainer-videos com URLs assinadas.</p></div><div className="card panel-card"><h3>Suporte</h3><a className="btn btn-secondary" href="https://wa.me/5500000000000">WhatsApp</a></div></div></>; }
