'use client';

export const dynamic = 'force-dynamic';

import { FormEvent, useEffect, useState } from 'react';
import { StudentShell } from '@/components/StudentShell';
import { useStudentSession } from '@/hooks/useStudentSession';
import { moneyFromCents } from '@/lib/access';
import { HEALTH_PROVIDERS } from '@/lib/health/providers';

export default function AlunoPage(){ return <StudentShell><AlunoContent /></StudentShell>; }
function AlunoContent(){ const {student,supabase}=useStudentSession(); const [workouts,setWorkouts]=useState<any[]>([]); const [habits,setHabits]=useState<any[]>([]); const [charges,setCharges]=useState<any[]>([]); const [metrics,setMetrics]=useState<any[]>([]); const [video,setVideo]=useState<string|null>(null); const [message,setMessage]=useState('');
async function load(){ if(!student)return; const [w,h,c,m]=await Promise.all([supabase.from('workouts').select('id,title,objective,workout_days(id,label,workout_exercises(id,sets,reps,suggested_load,rest_time,exercises(name,instructions,exercise_videos(id,title))))').eq('student_id',student.id).eq('status','active'),supabase.from('habits').select('*').eq('student_id',student.id).eq('status','active'),supabase.from('student_charges').select('*').eq('student_id',student.id).order('created_at',{ascending:false}),supabase.from('health_daily_metrics').select('*').eq('student_id',student.id).order('metric_date',{ascending:false}).limit(7)]); setWorkouts(w.data||[]); setHabits(h.data||[]); setCharges(c.data||[]); setMetrics(m.data||[]); }
useEffect(()=>{load();},[student]);
async function signVideo(videoId:string){ const {data:session}=await supabase.auth.getSession(); const res=await fetch(`/api/videos/signed-url?id=${videoId}`,{headers:{Authorization:`Bearer ${session.session?.access_token}`}}); const data=await res.json(); if(data.url)setVideo(data.url); if(data.error)setMessage(data.error); }
async function finishExercise(workoutExerciseId:string){ if(!student)return; await supabase.from('workout_logs').insert({student_id:student.id,trainer_id:student.trainer_id,workout_exercise_id:workoutExerciseId,status:'completed',completed_at:new Date().toISOString()}); setMessage('Série/exercício registrado e enviado para o personal.'); }
async function logHabit(habitId:string){ if(!student)return; await supabase.from('habit_logs').insert({habit_id:habitId,student_id:student.id,trainer_id:student.trainer_id,completed_at:new Date().toISOString()}); setMessage('Hábito registrado.'); }
async function anamnesis(e:FormEvent<HTMLFormElement>){ e.preventDefault(); if(!student)return; const f=new FormData(e.currentTarget); await supabase.from('anamneses').upsert({student_id:student.id,trainer_id:student.trainer_id,objective:f.get('objective'),weekly_frequency:f.get('weekly_frequency'),training_experience:f.get('training_experience'),training_location:f.get('training_location'),equipment:f.get('equipment'),injury_history:f.get('injury_history'),current_pain:f.get('current_pain'),medical_restrictions:f.get('medical_restrictions'),sleep_quality:f.get('sleep_quality'),stress_level:f.get('stress_level'),current_diet:f.get('current_diet'),smartwatch_use:f.get('smartwatch_use'),health_app:f.get('health_app'),notes:f.get('notes')},{onConflict:'student_id'}); setMessage('Anamnese salva.'); }
return <><div className="page-head"><div><span className="eyebrow">Área do aluno</span><h1>Olá, {student?.full_name}</h1><p>Treino do dia, evolução, hábitos, pagamentos, mensagens e conexões de saúde.</p></div></div>{message&&<div className="success">{message}</div>}{video&&<div className="card panel-card"><h3>Vídeo do exercício</h3><div className="video-box"><video src={video} controls playsInline /></div></div>}
<section id="treino" className="card panel-card"><h2>Meu treino</h2>{workouts.map(w=><div key={w.id}><h3>{w.title}</h3><p>{w.objective}</p>{w.workout_days?.map((d:any)=><div key={d.id}><span className="badge">{d.label}</span>{d.workout_exercises?.map((we:any)=><div className="card panel-card" key={we.id} style={{marginTop:12}}><h3>{we.exercises?.name}</h3><p>{we.exercises?.instructions}</p><p>{we.sets} séries · {we.reps} reps · carga {we.suggested_load||'—'} · descanso {we.rest_time||'—'}</p><div className="actions">{we.exercises?.exercise_videos?.[0]&&<button className="btn btn-secondary" onClick={()=>signVideo(we.exercises.exercise_videos[0].id)}>Assistir vídeo</button>}<button className="btn btn-primary" onClick={()=>finishExercise(we.id)}>Concluir série/exercício</button></div></div>)}</div>)}</div>)}{!workouts.length&&<div className="empty">Nenhum treino ativo enviado ainda.</div>}</section>
<section id="evolucao" className="card panel-card" style={{marginTop:18}}><h2>Minha evolução</h2><div className="grid-3">{metrics.map(m=><div className="stat" key={m.id}><strong>{m.metric_date}</strong><span>Passos: {m.steps??'Não informado pelo dispositivo.'}<br/>Sono: {m.sleep_minutes??'Não informado pelo dispositivo.'}<br/>Calorias: {m.active_calories??'Não informado pelo dispositivo.'}</span></div>)}</div></section>
<section id="habitos" className="card panel-card" style={{marginTop:18}}><h2>Hábitos</h2>{habits.map(h=><div className="row" key={h.id} style={{justifyContent:'space-between', padding:'10px 0', borderBottom:'1px solid var(--border)'}}><div><strong>{h.name}</strong><br/><span className="small">Meta: {h.target}</span></div><button className="btn btn-primary" onClick={()=>logHabit(h.id)}>Marcar hoje</button></div>)}</section>
<section id="pagamentos" className="card panel-card" style={{marginTop:18}}><h2>Pagamentos</h2><div className="table-card"><table><thead><tr><th>Descrição</th><th>Valor</th><th>Status</th><th>Ação</th></tr></thead><tbody>{charges.map(c=><tr key={c.id}><td>{c.description}</td><td>{moneyFromCents(c.amount_cents)}</td><td>{c.status}</td><td>{c.status==='paid'?'Pago':<a className="btn btn-secondary" href={c.payment_link || `/pagar/${c.id}`}>Pagar</a>}</td></tr>)}</tbody></table></div></section>
<section id="saude" className="card panel-card" style={{marginTop:18}}><h2>Conexões de Saúde</h2><div className="notice">Antes de conectar, você autoriza a coleta de passos, sono, atividades, frequência cardíaca, calorias e dados permitidos. Seu personal vinculado poderá ver esses dados. Você pode revogar quando quiser.</div><div className="grid-2" style={{marginTop:12}}>{Object.entries(HEALTH_PROVIDERS).map(([key,p])=><div className="card panel-card" key={key}><h3>{p.name}</h3><p>{p.description}</p><a className="btn btn-secondary" href={`/api/health/connect/${key}`}>Conectar</a></div>)}</div></section>
<section className="card panel-card" style={{marginTop:18}}><h2>Anamnese</h2><div className="notice">As informações preenchidas não substituem avaliação médica, nutricional ou fisioterapêutica.</div><form className="form-grid" onSubmit={anamnesis} style={{marginTop:12}}><div className="field"><label>Objetivo principal</label><input className="input" name="objective" /></div><div className="field"><label>Frequência por semana</label><input className="input" name="weekly_frequency" /></div><div className="field"><label>Experiência com treino</label><input className="input" name="training_experience" /></div><div className="field"><label>Local de treino</label><select className="select" name="training_location"><option>academia</option><option>casa</option><option>condomínio</option><option>ar livre</option><option>online</option></select></div><div className="field"><label>Equipamentos</label><input className="input" name="equipment" /></div><div className="field"><label>Histórico de lesões</label><textarea name="injury_history" /></div><div className="field"><label>Dores atuais</label><textarea name="current_pain" /></div><div className="field"><label>Restrições médicas</label><textarea name="medical_restrictions" /></div><div className="field"><label>Sono</label><input className="input" name="sleep_quality" /></div><div className="field"><label>Estresse</label><input className="input" name="stress_level" /></div><div className="field"><label>Alimentação atual</label><textarea name="current_diet" /></div><div className="field"><label>Relógio inteligente</label><input className="input" name="smartwatch_use" /></div><div className="field"><label>App de saúde usado</label><input className="input" name="health_app" /></div><div className="field"><label>Observações</label><textarea name="notes" /></div><button className="btn btn-primary">Salvar anamnese</button></form></section>
</>;}
